const en = {
    tagline: 'Cite from your library. No reference manager.',
    open: 'Open library file…',
    emptyHint: 'In Acade.me, export a library, collection, or writing project as Acade.me for Word (.json), send it to this computer, and open it here. It stays on this computer.',
    style: 'Style',
    search: 'Search your library',
    clickHint: 'Click a paper to cite it at the cursor, or tick several and cite them together.',
    citeSelected: 'Cite selected',
    citeTogether: 'Cite {n} together',
    bibliography: 'Insert bibliography',
    refresh: 'Refresh',
    refreshTitle: 'Renumber citations and rebuild the bibliography after editing',
    fine: 'Works offline from the file you open; nothing is sent anywhere.',
    privacy: 'Privacy',
    support: 'Support',
    noLibrary: 'No library open',
    libraryCount: '{name} — {n} papers',
    opened: 'Opened {name}.',
    notLibrary: 'This file is not an Acade.me library.',
    readFailed: 'Could not read that file.',
    maxTogether: 'Up to {n} papers can be cited together.',
    noCitations: 'No citations in this document yet.',
    updated: 'Updated {n} citation(s) and the bibliography ({style}).',
    missing: '{n} cited paper(s) are in neither this library nor the document — shown as [?]. Open the library they came from and refresh.',
    citeAtCursor: 'Cite at the cursor',
};
const it = {
    tagline: 'Cita dalla tua libreria. Senza gestore di riferimenti.',
    open: 'Apri file libreria…',
    emptyHint: 'In Acade.me esporta una libreria, una raccolta o un progetto di scrittura come Acade.me per Word (.json), invialo a questo computer e aprilo qui. Resta su questo computer.',
    style: 'Stile',
    search: 'Cerca nella libreria',
    clickHint: 'Fai clic su un articolo per citarlo al cursore, oppure selezionane diversi e citali insieme.',
    citeSelected: 'Cita selezionati',
    citeTogether: 'Cita {n} insieme',
    bibliography: 'Inserisci bibliografia',
    refresh: 'Aggiorna',
    refreshTitle: 'Rinumera le citazioni e ricostruisci la bibliografia dopo le modifiche',
    fine: 'Funziona offline dal file che apri; non viene inviato nulla.',
    privacy: 'Privacy',
    support: 'Assistenza',
    noLibrary: 'Nessuna libreria aperta',
    libraryCount: '{name} — {n} articoli',
    opened: 'Aperta {name}.',
    notLibrary: 'Questo file non è una libreria Acade.me.',
    readFailed: 'Impossibile leggere il file.',
    maxTogether: 'Si possono citare insieme fino a {n} articoli.',
    noCitations: 'Ancora nessuna citazione in questo documento.',
    updated: 'Aggiornate {n} citazioni e la bibliografia ({style}).',
    missing: '{n} articoli citati non sono né in questa libreria né nel documento — mostrati come [?]. Apri la libreria da cui provengono e aggiorna.',
    citeAtCursor: 'Cita al cursore',
};
const fr = {
    tagline: 'Citez depuis votre bibliothèque. Sans gestionnaire de références.',
    open: 'Ouvrir le fichier de bibliothèque…',
    emptyHint: 'Dans Acade.me, exportez une bibliothèque, une collection ou un projet d’écriture en Acade.me pour Word (.json), envoyez-le sur cet ordinateur et ouvrez-le ici. Il reste sur cet ordinateur.',
    style: 'Style',
    search: 'Rechercher dans la bibliothèque',
    clickHint: 'Cliquez sur un article pour le citer au curseur, ou cochez-en plusieurs pour les citer ensemble.',
    citeSelected: 'Citer la sélection',
    citeTogether: 'Citer les {n} ensemble',
    bibliography: 'Insérer la bibliographie',
    refresh: 'Actualiser',
    refreshTitle: 'Renuméroter les citations et reconstruire la bibliographie après modification',
    fine: 'Fonctionne hors ligne à partir du fichier ouvert ; rien n’est envoyé.',
    privacy: 'Confidentialité',
    support: 'Assistance',
    noLibrary: 'Aucune bibliothèque ouverte',
    libraryCount: '{name} — {n} articles',
    opened: '{name} ouverte.',
    notLibrary: 'Ce fichier n’est pas une bibliothèque Acade.me.',
    readFailed: 'Impossible de lire ce fichier.',
    maxTogether: 'Jusqu’à {n} articles peuvent être cités ensemble.',
    noCitations: 'Aucune citation dans ce document pour l’instant.',
    updated: '{n} citation(s) et la bibliographie mises à jour ({style}).',
    missing: '{n} article(s) cité(s) ne sont ni dans cette bibliothèque ni dans le document — affichés [?]. Ouvrez leur bibliothèque d’origine et actualisez.',
    citeAtCursor: 'Citer au curseur',
};
const ru = {
    tagline: 'Цитируйте из своей библиотеки. Без менеджера ссылок.',
    open: 'Открыть файл библиотеки…',
    emptyHint: 'В Acade.me экспортируйте библиотеку, коллекцию или проект текста как «Acade.me для Word (.json)», отправьте файл на этот компьютер и откройте здесь. Он остаётся на этом компьютере.',
    style: 'Стиль',
    search: 'Поиск в библиотеке',
    clickHint: 'Нажмите на статью, чтобы процитировать её у курсора, или отметьте несколько и процитируйте вместе.',
    citeSelected: 'Цитировать выбранные',
    citeTogether: 'Цитировать {n} вместе',
    bibliography: 'Вставить список литературы',
    refresh: 'Обновить',
    refreshTitle: 'Перенумеровать ссылки и пересобрать список литературы после правок',
    fine: 'Работает офлайн с открытым файлом; ничего никуда не отправляется.',
    privacy: 'Конфиденциальность',
    support: 'Поддержка',
    noLibrary: 'Библиотека не открыта',
    libraryCount: '{name} — статей: {n}',
    opened: 'Открыта {name}.',
    notLibrary: 'Этот файл не является библиотекой Acade.me.',
    readFailed: 'Не удалось прочитать файл.',
    maxTogether: 'Вместе можно процитировать до {n} статей.',
    noCitations: 'В этом документе пока нет ссылок.',
    updated: 'Обновлено ссылок: {n}, и список литературы ({style}).',
    missing: 'Процитированных статей нет ни в библиотеке, ни в документе: {n} — показаны как [?]. Откройте их библиотеку и обновите.',
    citeAtCursor: 'Цитировать у курсора',
};
const pt = {
    tagline: 'Cite da sua biblioteca. Sem gerenciador de referências.',
    open: 'Abrir arquivo da biblioteca…',
    emptyHint: 'No Acade.me, exporte uma biblioteca, coleção ou projeto de escrita como Acade.me para Word (.json), envie para este computador e abra aqui. Ele fica neste computador.',
    style: 'Estilo',
    search: 'Buscar na biblioteca',
    clickHint: 'Clique em um artigo para citá-lo no cursor, ou marque vários e cite-os juntos.',
    citeSelected: 'Citar selecionados',
    citeTogether: 'Citar {n} juntos',
    bibliography: 'Inserir bibliografia',
    refresh: 'Atualizar',
    refreshTitle: 'Renumerar as citações e refazer a bibliografia após editar',
    fine: 'Funciona offline a partir do arquivo aberto; nada é enviado.',
    privacy: 'Privacidade',
    support: 'Suporte',
    noLibrary: 'Nenhuma biblioteca aberta',
    libraryCount: '{name} — {n} artigos',
    opened: '{name} aberta.',
    notLibrary: 'Este arquivo não é uma biblioteca do Acade.me.',
    readFailed: 'Não foi possível ler o arquivo.',
    maxTogether: 'Até {n} artigos podem ser citados juntos.',
    noCitations: 'Ainda não há citações neste documento.',
    updated: '{n} citação(ões) e a bibliografia atualizadas ({style}).',
    missing: '{n} artigo(s) citado(s) não estão nesta biblioteca nem no documento — aparecem como [?]. Abra a biblioteca de origem e atualize.',
    citeAtCursor: 'Citar no cursor',
};
const ro = {
    tagline: 'Citează din biblioteca ta. Fără manager de referințe.',
    open: 'Deschide fișierul bibliotecii…',
    emptyHint: 'În Acade.me exportă o bibliotecă, o colecție sau un proiect de scriere ca Acade.me pentru Word (.json), trimite-l pe acest calculator și deschide-l aici. Rămâne pe acest calculator.',
    style: 'Stil',
    search: 'Caută în bibliotecă',
    clickHint: 'Clic pe o lucrare ca s-o citezi la cursor, sau bifează mai multe și citează-le împreună.',
    citeSelected: 'Citează selecția',
    citeTogether: 'Citează {n} împreună',
    bibliography: 'Inserează bibliografia',
    refresh: 'Actualizează',
    refreshTitle: 'Renumerotează citările și refă bibliografia după editare',
    fine: 'Funcționează offline din fișierul deschis; nu se trimite nimic.',
    privacy: 'Confidențialitate',
    support: 'Asistență',
    noLibrary: 'Nicio bibliotecă deschisă',
    libraryCount: '{name} — {n} lucrări',
    opened: 'S-a deschis {name}.',
    notLibrary: 'Acest fișier nu este o bibliotecă Acade.me.',
    readFailed: 'Fișierul nu a putut fi citit.',
    maxTogether: 'Se pot cita împreună cel mult {n} lucrări.',
    noCitations: 'Încă nicio citare în acest document.',
    updated: 'Au fost actualizate {n} citări și bibliografia ({style}).',
    missing: '{n} lucrări citate nu sunt nici în această bibliotecă, nici în document — apar ca [?]. Deschide biblioteca lor și actualizează.',
    citeAtCursor: 'Citează la cursor',
};
const ja = {
    tagline: 'ライブラリから引用。文献管理ソフトは不要です。',
    open: 'ライブラリ ファイルを開く…',
    emptyHint: 'Acade.me でライブラリ、コレクション、執筆プロジェクトを「Acade.me for Word (.json)」として書き出し、このパソコンに送ってここで開きます。ファイルはこのパソコンに残ります。',
    style: 'スタイル',
    search: 'ライブラリを検索',
    clickHint: '論文をクリックするとカーソル位置に引用されます。複数にチェックしてまとめて引用することもできます。',
    citeSelected: '選択した論文を引用',
    citeTogether: '{n} 件をまとめて引用',
    bibliography: '参考文献リストを挿入',
    refresh: '更新',
    refreshTitle: '編集後に引用番号を振り直し、参考文献リストを作り直します',
    fine: '開いたファイルだけでオフライン動作し、何も送信しません。',
    privacy: 'プライバシー',
    support: 'サポート',
    noLibrary: 'ライブラリが開かれていません',
    libraryCount: '{name} — {n} 件',
    opened: '{name} を開きました。',
    notLibrary: 'このファイルは Acade.me のライブラリではありません。',
    readFailed: 'ファイルを読み込めませんでした。',
    maxTogether: 'まとめて引用できるのは {n} 件までです。',
    noCitations: 'この文書にはまだ引用がありません。',
    updated: '引用 {n} 件と参考文献リストを更新しました（{style}）。',
    missing: '引用した論文 {n} 件がライブラリにも文書にもありません（[?] と表示）。元のライブラリを開いて更新してください。',
    citeAtCursor: 'カーソル位置に引用',
};
const TABLE = { en, it, fr, ru, pt, ro, ja };
// "it-IT" → Italian; anything else → English
export const stringsFor = (displayLanguage) => { var _a; return (_a = TABLE[(displayLanguage !== null && displayLanguage !== void 0 ? displayLanguage : 'en').slice(0, 2).toLowerCase()]) !== null && _a !== void 0 ? _a : en; };
export const fill = (template, values) => template.replace(/\{(\w+)\}/g, (match, key) => (key in values ? String(values[key]) : match));
